### PR TITLE
[kernel] Upgrade Linux kernel to 5.5

### PR DESCRIPTION
**Pull request by DylanVanAssche**

### CODE REVIEW

**Comment by carlosgonz0** [comment]
Hi any plans to merge this PR, then to get fix display-volt. Please new build of kernel.

**Comment by piggz** [comment]
@DylanVanAssche is this the kernel I sent you?

**Comment by carlosgonz0** [comment]
> @DylanVanAssche

**Comment by piggz** [comment]
> > @DylanVanAssche

Dont fret, im just testing a new kernel build, and will get dylan to test it and commit it soon (tm)

**Comment by carlosgonz0** [comment]
> Dont fret, im just testing a new kernel build, and will get dylan to test it and commit it soon (tm)

Thankful  @piggz

**Comment by piggz** [comment]
> > Dont fret, im just testing a new kernel build, and will get dylan to test it and commit it soon (tm)
> 
> Thankful @piggz

Ive uploaded my kernel 5.5. to OBS.  Please try it out incase I didnt package it correctly.

You will also want to install the updated config package, and I also updated Mesa to 20.0.2

**Comment by carlosgonz0** [comment]
Like "version --dup" on sf?

**Comment by piggz** [comment]
> Like "version --dup" on sf?

Personally, i zypper ref && zypper dup, but that should work

**Comment by carlosgonz0** [comment]
> > Like "version --dup" on sf?
> 
> Personally, i zypper ref && zypper dup, but that should work

ok , I will update now.

**Comment by carlosgonz0** [comment]
I tested, it work good new kernel. Power manager still not work, Bluetooth page is broke, also the  volume of the system can not be controlled by physical buttons, native browser still broken, also wake up the  screen get a  spin delay on screen,  introduced on this little update I guess.  I just reporting on my quick test.   Thank you for all ur work.

**Comment by DylanVanAssche** [comment]
Bluetooth page works... Remove your battery and try again.
There's a known issue across all OSes: the BT driver fails to work after a reboot or power off/on. A real power cycle (BT hardware is connected to the battery) helps for the next boot only.

The volume control is broken, the right modules are there but for some reason the volume control module doesn't change the main volume. `alsamixer` shows more: `Line out` is the one you need.

**Comment by carlosgonz0** [comment]
Finally @DylanVanAssche is here. :  )
Ok i will check bluetooth page after remove the batt.

**Comment by DylanVanAssche** [comment]
> Finally @DylanVanAssche is here. : )

I was always here :) Although, we wanted to first fix the kernel for SFOS :)

**Comment by carlosgonz0** [comment]
@DylanVanAssche @piggz  battery charging not work ATM, is fixed here https://github.com/sailfish-on-dontbeevil/droid-hal-kernel-pine/releases ? . also how to get USB_C-Power-Delivery work in SF I buyed a usb-c pd 2.0 charger to  my pinephone. So I guess that the usb_c-PD2.0 controller of pinephone is drived by  
`CONFIG_TYPEC_ANX7688=y`
https://www.analogix.com/en/products/convertersbridges/anx7688 < pinephone usb-c controller

**Pull request merged**
